#!/bin/bash

USERNAME="thermal_monitoring"
BASE=/usr/local/bin/pi-therm-monitoring
adduser --system $USERNAME

chmod 774 "$BASE/thermal_camera.sh"
chmod 774 "$BASE/wifi_reconnexion.sh"
VENV_DIR=$BASE/venv

# Create the virtual environment
python3 -m venv $VENV_DIR

# Activate the virtual environment
. $VENV_DIR/bin/activate

# Install required packages
$VENV_DIR/bin/pip install -r /usr/local/bin/pi-therm-monitoring/requirements.txt
cd /usr/local/bin/pi-therm-monitoring/
npm install
# Deactivate the venv
deactivate

set -e

sudo systemctl enable thermal_camera.service
sudo systemctl start thermal_camera.service
sudo systemctl enable wifi_reconnexion.service
sudo systemctl start wifi_reconnexion.service