on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: "Build the script into deb file"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y debhelper

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Setting up files
        run: |
          # Create necessary directories
          mkdir -p ./pi-therm-monitoring/DEBIAN
          mkdir -p ./pi-therm-monitoring/usr/local/bin/pi-therm-monitoring/
          mkdir -p ./pi-therm-monitoring/lib/systemd/system
          
          # Copy necessary files
          cp ./scripts/* ./pi-therm-monitoring/usr/local/bin/pi-therm-monitoring/
          cp ./deb-structure/DEBIAN/* ./pi-therm-monitoring/DEBIAN/
          chmod 775 ./pi-therm-monitoring/DEBIAN/postinst
          chmod 775 ./pi-therm-monitoring/DEBIAN/prerm
          cat ./pi-therm-monitoring/DEBIAN/control
          echo -e "Version: 0.0" >> ./pi-therm-monitoring/DEBIAN/control
          cp ./deb-structure/thermal_camera.service ./pi-therm-monitoring/lib/systemd/system/thermal_camera.service
          cat ./pi-therm-monitoring/DEBIAN/control
          ls ./pi-therm-monitoring/DEBIAN/

      - name: Build the deb file
        run: dpkg-deb --build pi-therm-monitoring

      - name: Upload .deb package
        uses: actions/upload-artifact@v4
        with:
          name: pi-thermal-monitoring
          path: ./pi-therm-monitoring.deb
      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./pi-therm-monitoring.deb
          prerelease: false
