on:
  push:
    branches:
      -main
  workflow_dispatch:

jobs:
  build:
    name: "Build the script into deb a file"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt install debhelper
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Settings up files
        run: |
          mkdir -p ./pi-therm-monitoring/DEBIAN
          mkdir -p ./pi-therm-monitoring/usr/local/bin/pi-therm-monitoring/
          cp ./scripts/*.py ./pi-therm-monitoring/usr/local/bin/pi-therm-monitoring/
          cp ./deb-structure/DEBIAN/control ./pi-therm-monitoring/DEBIAN/control
          echo "Version: 0.0" >> ./pi-therm-monitoring/DEBIAN/control
          cp ./deb-structure/DEBIAN/thermal_camera.service ./pi-therm-monitoring/DEBIAN/thermal_camera.service
          cat ./pi-therm-monitoring/DEBIAN/control

      - name: Build the deb file
        run: dpkg-deb --build pi-therm-monitoring

      - name: Upload .deb package
        uses: actions/upload-artifact@v4
        with:
          # Name of the artifact to upload.
          # Optional. Default is 'artifact'
          name: pi-thermal-monitoring
      
          # A file, directory or wildcard pattern that describes what to upload
          # Required.
          path: pi-therm-monitoring.deb
                
